backend:
  name: github
  repo: robigan/robigan-blog
  branch: main
  base_url: https://archives.robigan.com/
  auth_endpoint: /api/auth

media_folder: "static/uploads"
public_folder: "/uploads"

local_backend: true

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Meta Description"
        name: "description"
        widget: "string"

      - label: "Summary"
        name: "summary"
        widget: "string"
        required: false

      - label: "Robots"
        name: "robots"
        widget: "string"
        hint: "https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#directives"
        default: "all"

      - label: "Menu"
        hint: "When a value is provided, a link to this article will appear in the named menus. Valid values are main or footer."
        name: "menu"
        widget: "select"
        options:
          - "main"
          - "footer"
        required: false
      
      - label: "Series"
        hint: "Array of series the article belongs to, we recommend using only one series per article."
        name: "series"
        widget: "list"
        required: false
      
      - label: "Series Order"
        hint: "Number of the article within the series."
        name: "series_order"
        widget: "number"
        required: false

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false

      - label: "Draft"
        hint: "Whether or not this article is considered a rough draft by Hugo."
        name: "draft"
        widget: "boolean"
        default: false

      - label: "Body"
        name: "body"
        widget: "markdown"
      
      # - label: "Show Date"
      #   hint: "Whether or not the article date is displayed. "
      #   name: "showDate"
      #   widget: "boolean"
      #   required: false

      # - label: "Views"
      #   hint: "Whether or not the article views should be displayed in lists and detailed view."
      #   name: "showViews"
      #   widget: "boolean"
      #   required: false

      # - label: "Likes"
      #   hint: "Whether or not the article likes should be displayed in lists and detailed view."
      #   name: "showLikes"
      #   widget: "boolean"
      #   required: false

      # - label: "Updated Date"
      #   hint: "Whether or not the date the article was updated is displayed."
      #   name: "showDateUpdated"
      #   widget: "boolean"
      #   required: false

      # - label: "Pagination"
      #   hint: "Whether or not the next/previous article links are displayed in the article footer."
      #   name: "showPagination"
      #   widget: "boolean"
      #   required: false

      # - label: "Reading Time"
      #   hint: ""
      #   name: "showReadingTime"
      #   widget: "boolean"
      #   required: false

      # - label: "Taxonomies"
      #   hint: "Whether or not the taxonomies that relate to this article are displayed."
      #   name: "showTaxonomies"
      #   widget: "boolean"
      #   required: false

      # - label: "Table of Contents"
      #   hint: "Whether or not the table of contents is displayed on this article."
      #   name: "showTableOfContents"
      #   widget: "boolean"
      #   required: false

      # - label: "Word Count"
      #   hint: "Whether or not the article word count is displayed."
      #   name: "showWordCount"
      #   widget: "boolean"
      #   required: false

      # - label: "Show Summary"
      #   hint: "Whether or not the article summary should be displayed on list pages."
      #   name: "showSummary"
      #   widget: "boolean"
      #   required: false

      # - label: "Add to Sitemap"
      #   hint: "Whether or not this article is included in the generated /sitemap.xml file."
      #   name: "xml"
      #   widget: "boolean"
      #   required: false